### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by kmoto2** [tedtoal/floatToString#1]
Hi, when I run the following test:
  #include <floatToString.h>
  char S[15];
  float test = 127.94;
  for (int i = 0; i <= 7; i++) {
    floatToString(test, S, sizeof(S), 1);
    Serial.print("Original Value = ");
    Serial.print(test);
    Serial.print(", floatToStringValue = ");
    Serial.println(S);
    test = test + 0.01;
  }
I get the following, and the "127.10" values are not correct (should be "128.0"):
Original Value = 127.94, floatToStringValue = 127.9
Original Value = 127.95, floatToStringValue = 127.10
Original Value = 127.96, floatToStringValue = 127.10
Original Value = 127.97, floatToStringValue = 127.10
Original Value = 127.98, floatToStringValue = 127.10
Original Value = 127.99, floatToStringValue = 127.10
Original Value = 128.00, floatToStringValue = 128.0
Original Value = 128.01, floatToStringValue = 128.0

**Comment by tedtoal** [comment]
Thanks so much for finding this!  Sorry it took me a while to get to this.

I’ve fixed the bug and am awaiting for it to show up in the Arduino library, but that can take a couple hours or possibly days, not sure.  But you can edit floatToString.cpp in libraries/floatToString/src and put this in place of existing code.  You might want to save the original file and then put it back in a couple days, because editing it might prevent the Arduino IDE from doing an automatic update.

I tested this not on an Arduino but on my iMac with a cpp program.  It should be okay, but please let me know if you find anything else!

The new release is 1.3.1
